package scripts;

import java.io.*;
import java.lang.String;
import java.util.*;

public class CoreDiversityAnalysis extends Script {
	public static String title = "Core Diversity Analysis";
	public static String b_desc = "A workflow for running a core set of QIIME diversity analyses.";

	public CoreDiversityAnalysis() {
		// set up script name, command, and descriptions
		this.link = "http://qiime.org/scripts/core_diversity_analyses.html";
		this.c_name = SCRIPTS_PATH + "core_diversity_analyses.py";
		this.l_desc = "This script plugs several QIIME diversity analyses together to form a basic workflow beginning with a BIOM table, mapping file, and optional phylogenetic tree.<br><br>The included scripts are those run by the workflow scripts alpha_rarefaction.py, beta_diversity_through_plots.py, summarize_taxa_through_plots.py, plus the (non-workflow) scripts make_distance_boxplots.py, compare_alpha_diversity.py, and group_significance.py. To update parameters to the workflow scripts, you should pass the same parameters file that you would pass if calling the workflow script directly.<br><br>Additionally, a table summary is generated by running the ‘biom summarize-table’ command (part of the biom-format package). To update parameters to this command, your parameters file should use ‘biom-summarize-table’ (without quotes) as the script name. See http://qiime.org/documentation/qiime_parameters_files.html for more details.";
		this.output_desc = "Run diversity analyses at 20 sequences/sample, with categorical analyses focusing on the SampleType and day categories. ALWAYS SPECIFY ABSOLUTE FILE PATHS (absolute path represented here as $PWD, but will generally look something like /home/ubuntu/my_analysis/).";

		// set up the required otpions
		this.r_options = new ArrayList<Option>(4);
		this.r_options.add(new Option("Input BIOM FIle", "-i", Option.PATH, "The input biom file [REQUIRED]"));
		this.r_options.add(new Option("Output", "-o", Option.PATH, "The output directory [REQUIRED]"));
		this.r_options.add(new Option("Mapping File", "-m", Option.PATH, "The mapping filepath [REQUIRED]"));
		this.r_options.add(new Option("Sampling Depth", "-e", Option.NUM, "Sequencing depth to use for even sub-sampling and maximum rarefaction depth. You should review the output of the ‘biom summarize-table’ command to decide on this value."));

		// set up the extra options
		this.e_options = new ArrayList<Option>(12);
		this.e_options.add(new Option("Parameter File", "-p", Option.PATH, "Path to the parameter file, which specifies changes to the default behavior. For more information, see www.qiime.org/documentation/qiime_parameters_files.html [if omitted, default values will be used]"));
		this.e_options.add(new Option("Parallel", "-a", Option.NOARG, "Run in parallel where available. Specify number of jobs to start with -O or in the parameters file. [default: False]"));
		this.e_options.add(new Option("Nonphylogenetic Diversity", "--nonphylogenetic_diversity", Option.NOARG, "Apply non-phylogenetic alpha (chao1 and observed_otus) and beta (bray_curtis) diversity calculations. This is useful if, for example, you are working with non-amplicon BIOM tables, or if a reliable tree is not available (e.g., if you’re working with ITS amplicons) [default: False]"));
		this.e_options.add(new Option("Suppress Taxa Summary", "--suppress_taxa_summary", Option.NOARG, "Suppress generation of taxa summary plots. [default: False]"));
		this.e_options.add(new Option("Suppress Beta Diversity", "--suppress_beta_diversity", Option.NOARG, "Suppress beta diversity analyses. [default: False]"));
		this.e_options.add(new Option("Supress Alpha Diversity", "--suppress_alpha_diversity", Option.NOARG, "Suppress alpha diversity analyses. [default: False]"));
		this.e_options.add(new Option("Suppress Group Significance", "--suppress_group_significance", Option.NOARG, "Suppress OTU/category significance analysis. [default: False]"));
		this.e_options.add(new Option("Tree File", "-t", Option.PATH, "Path to the tree file if one should be used. Required unless –nonphylogenetic_diversity is passed. [default: no tree will be used]"));
		this.e_options.add(new Option("Categories", "-c", Option.INPUT, "The metadata category or categories to compare (i.e., column headers in the mapping file) for categorical analyses. These should be passed as a comma-separated list. [default: None; do not perform categorical analyses]"));
		this.e_options.add(new Option("Print Only", "-w", Option.NOARG, "Print the commands but don’t call them – useful for debugging or recovering from failed runs. [default: False]"));
		this.e_options.add(new Option("Recover From Failure", "--recover_from_failure", Option.NOARG, "Don’t fail if output directory exists, but attempt to recover from the failed run. [default: False]"));
		this.e_options.add(new Option("Jobs to Start", "-O", Option.NUM, "Number of jobs to start. NOTE: you must also pass -a to run in parallel, this defines the number of jobs to be started if and only if -a is passed [default: 1]"));
	
	}
}
