package scripts;

import java.io.*;
import java.lang.String;
import java.util.*;

public class MergeOTUMaps extends Script {
	public static String title = "Merge OTU Maps";
	public static String b_desc = "Merge OTU mapping files";

	public MergeOTUMaps() {
		// set up script name, command, and descriptions
		this.link = "http://qiime.org/scripts/merge_otu_maps.html";
		this.c_name = SCRIPTS_PATH + "merge_otu_maps.py";
		this.l_desc = "This script merges OTU mapping files generated by denoise_wrapper.py and/or pick_otus.py";
		this.output_desc = "The result of this script is an OTU mapping file.";

		// set up the required otpions
		this.r_options = new ArrayList<Option>(2);
		this.r_options.add(new Option("OTU Maps", "-i", Option.PATH, 0, "The otu map filepaths, comma-separated and ordered as the OTU pickers were run [REQUIRED]"));
		this.r_options.add(new Option("Output", "-o", Option.PATH, "Path to write output OTU map [REQUIRED]"));

		// set up the extra options
		this.e_options = new ArrayList<Option>(1);
		this.e_options.add(new Option("Failures Filepath", "-f", Option.PATH, "Failures filepath, if applicable"));
	
	}
}